[package]
name = "webview_deno"
version = "0.6.0-pre.0"
authors = ["Elias Sjögreen", "Filippo Rossi"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.88.0"
webview_official = "0.2.0"
serde = "1.0.125"
