[package]
name = "webview_deno"
version = "0.5.0"
authors = ["Elias Sjögreen", "Filippo Rossi"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.67.0"
deno_json_op = "0.1.1"
webview-official-sys = "0.1.0"
