[package]
name = "webview_deno"
version = "0.7.0-pre.2"
authors = ["Elias Sjögreen <eliassjogreen1@gmail.com>", "Filippo Rossi"]
edition = "2021"

[lib]
path = "src/bindings.rs"
crate-type = ["cdylib"]

[dependencies]
webview-official-sys = { path = "../webview_rust/webview-official-sys" }
