name: Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "src/ffi.ts"
      - "webview/**"

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: install webkit2gtk (Linux)
        if: matrix.platform == "ubuntu-latest"
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Build dynamic library
        run: deno task build


      - name: Upload Artifacts (Windows)
        if: matrix.platform == "windows-latest"
        uses: actions/upload-artifact@v1
        with: 
          name: windows-dynamic-library
          path: |
            build/webview.dll
            build/Webview2Loader.dll
  
      - name: Upload Artifacts (Linux)
        if: matrix.platform == "ubuntu-latest"
        uses: actions/upload-artifact@v1
        with: 
          name: linux-dynamic-library
            build/libwebview.so
        
      - name: Upload Artifacts (Darwin)
        if: matrix.platform == "macos-latest"
        uses: actions/upload-artifact@v1
        with: 
          name: darwin-dynamic-library
            build/libwebview.x86_64.dylib

#      - name: Release Plugin
#        uses: softprops/action-gh-release@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: "webview_deno release"
#          draft: true
#          files: |
#            build/libwebview.x86_64.dylib
#            build/libwebview.so
#            build/webview.dll
#            build/Webview2Loader.dll
