on: [push, pull_request]

name: Checks

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install stable deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
    
      - name: Install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev

      - name: Run check
        run: deno task check

      - name: Run fmt
        run: deno task fmt:check

      - name: Run lint
        run: deno task lint
